"""remove target_id from post

Revision ID: 2605c44c654d
Revises: dd03fbb0f66f
Create Date: 2021-02-23 23:28:17.782303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2605c44c654d'
down_revision = 'dd03fbb0f66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.drop_column('post', 'target_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_ibfk_2', 'post', 'target', ['target_id'], ['id'])
    # ### end Alembic commands ###
