"""change target model

Revision ID: 5c8cd410acef
Revises: c9b956b198e9
Create Date: 2021-02-22 15:44:19.531937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8cd410acef'
down_revision = 'c9b956b198e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('reliability', sa.Float(), nullable=True))
    op.add_column('target', sa.Column('result', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'result')
    op.drop_column('target', 'reliability')
    # ### end Alembic commands ###
