"""connect target to post

Revision ID: 617f8d9b15a1
Revises: 5c8cd410acef
Create Date: 2021-02-23 01:31:41.034807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617f8d9b15a1'
down_revision = '5c8cd410acef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('target_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'target', ['target_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'target_id')
    # ### end Alembic commands ###
