"""old indexes removed

Revision ID: 841244715573
Revises: 37f8e87252bd
Create Date: 2020-11-26 10:03:23.596459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841244715573'
down_revision = '37f8e87252bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('postattachmentmodel_post_id', table_name='post_attachment')
    op.drop_index('posttimestampmodel_post_id', table_name='post_timestamp')
    op.drop_index('postmodel_source_id', table_name='posts')
    op.drop_index('tasksourcemodel_source_id', table_name='task_sources')
    op.drop_index('tasksourcemodel_task_id', table_name='task_sources')
    op.drop_constraint(None, 'task_sources', type_='foreignkey')
    op.create_foreign_key(None, 'task_sources', 'tasks', ['task_id'], ['id'])
    op.drop_index('taskmodel_access_profile_id', table_name='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('taskmodel_access_profile_id', 'tasks', ['access_profile_id'], unique=False)
    op.drop_constraint(None, 'task_sources', type_='foreignkey')
    op.create_foreign_key(None, 'task_sources', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index('tasksourcemodel_task_id', 'task_sources', ['task_id'], unique=False)
    op.create_index('tasksourcemodel_source_id', 'task_sources', ['source_id'], unique=False)
    op.create_index('postmodel_source_id', 'posts', ['source_id'], unique=False)
    op.create_index('posttimestampmodel_post_id', 'post_timestamp', ['post_id'], unique=False)
    op.create_index('postattachmentmodel_post_id', 'post_attachment', ['post_id'], unique=False)
    # ### end Alembic commands ###
