"""updating

Revision ID: 860d4e755a45
Revises: 841244715573
Create Date: 2020-11-26 10:41:13.040659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860d4e755a45'
down_revision = '841244715573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('taskmodel_access_profile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('taskmodel_access_profile_id', ['access_profile_id'], unique=False)

    # ### end Alembic commands ###
