"""added title to target

Revision ID: 8f6c73ed9073
Revises: 2605c44c654d
Create Date: 2021-02-26 09:58:16.882500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6c73ed9073'
down_revision = '2605c44c654d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'title')
    # ### end Alembic commands ###
