"""added cascade delete to task

Revision ID: ef379eab1f81
Revises: feb538dc09f3
Create Date: 2021-02-28 21:45:35.723439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef379eab1f81'
down_revision = 'feb538dc09f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_source_ibfk_2', 'task_source', type_='foreignkey')
    op.create_foreign_key("task_source_ibfk_2", 'task_source', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint("value_check", "post", "value in (-1, 0, 1)")
    op.create_check_constraint("fit_value_check", "post", "fit_value in (-1, 0, 1)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("task_source_ibfk_2", 'task_source', type_='foreignkey')
    op.create_foreign_key('task_source_ibfk_2', 'task_source', 'task', ['task_id'], ['id'])
    op.drop_constraint("value_check")
    op.drop_constraint("fit_value_check")
    # ### end Alembic commands ###
