"""added title to task table

Revision ID: f2769554e0ec
Revises: ef379eab1f81
Create Date: 2021-03-03 08:41:37.123420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2769554e0ec'
down_revision = 'ef379eab1f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
