"""addet fit_value to post

Revision ID: feb538dc09f3
Revises: 8f6c73ed9073
Create Date: 2021-02-28 14:31:04.325546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb538dc09f3'
down_revision = '8f6c73ed9073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('fit_value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'fit_value')
    # ### end Alembic commands ###
