export const LOAD_ACCESS_PROFILES = "LOAD_ACCESS_PROFILES";
export const ADD_ACCESS_PROFILE = "ADD_ACCESS_PROFILE";
export const UPDATE_ACCESS_PROFILE = "UPDATE_ACCESS_PROFILE";
export const DELETE_ACCESS_PROFILE = "DELETE_ACCESS_PROFILE";